services:
  - type: web
    name: fraud-api
    runtime: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    workingDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
    buildFilter:
      paths: ["backend/**"]
